name: Rpgcore
version: ${project.version}
main: me.prismskey.rpgcore.Rpgcore
api-version: 1.16
authors: [prismskey]
description: RPG Core for custom RPG server
depend: [WorldGuard, Vault, NBTAPI]
commands:
  dscore:
    description: admin-commands
    permission: dscore.admin
  join:
    description: joining an arena
  leave:
    description: leaving an arena
    aliases:
      - exit
      - quit
  givepermissionreward:
    description: gives a permission if player does not already have it otherwise gives specified amount of money.
    permission: dscore.admin.lootcrate
    aliases:
      - gp
  rejoin:
    description: rejoin an arena
  fillblocks:
    description: used by the dungeon system to fill blocks
    permission: dscore.admin.fillblocks
  pvp:
    description: toggle pvp
  party:
    description: used to handle parties for dungeon raiding
    usage: /party create/join/invite/leave/disband (player_name)
  savecustomitem:
    description: save custom items for use in crafting recipes
    usage: /savecustomitem
    permission: dscore.admin.savecustomitem
  getcustomitems:
    description: gets custom items
    usage: /getcustomitems
    permission: dscore.admin.getcustomitems