name: Rpgcore
version: ${project.version}
main: me.prismskey.rpgcore.Rpgcore
api-version: 1.16
authors: [prismskey]
description: RPG Core for custom RPG server
depend: [WorldGuard, mcMMO, Vault, NBTAPI]
commands:
  dscore:
    description: admin-commands
    permission: dscore.admin
  join:
    description: joining an arena
  leave:
    description: leaving an arena
    aliases:
      - exit
      - quit
  givepermissionreward:
    description: gives a permission if player does not already have it otherwise gives specified amount of money.
    permission: dscore.admin.lootcrate
    aliases:
      - gp